name: Drugs
version: 6.4-SNAPSHOT
main: me.theminddroid.drugs.DrugsPlugin
api-version: "1.20"
authors: [TheMindDroid, AlexAn75541]
description: Gives specific items drug effects (Updated with more features by AlexAn75541)
commands:
  drugs:
    description: An admin tool to spawn drugs.
    usage: /<command>
